import '../../../common/definations.dart';

const imageAssetsRes = '''///This file is automatically generated.
///DO NOT EDIT, all your changes would be lost.
///dart run module_generator:generate_asset [customer, staff]
part of 'assets.dart';

class ImageAssets {
  ImageAssets();$contentKey
}
''';
